on:
  push:
    tags:
      - "*"

jobs:
  setup_and_build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update package.json version
        run: |
          export TAG=$VERSION
          node update-versions.js
        working-directory: ./scripts

      - name: Build
        run: pnpm run build

      - name: Override symlinks
        run: |
          for d in ./packages/*; do
              rm "$d"/README.md
              cp ./README.md "$d"
          done

      - name: Pack packages
        run: pnpm run pack-packages

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm publish --access public --no-git-checks --filter './packages/**'
